import Head from "next/head";
import Link from "next/link";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { AiOutlineTwitter, AiFillLinkedin, AiFillGithub } from "react-icons/ai";
import Image from "next/legacy/image";
import deved from "../public/dev-ed-wave.png";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import { useState } from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Cody Coderson</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="text-xl font-burtons">code code code</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className="cursor-pointer text-2xl" />
              </li>
              <li>
                <a className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8" href="#">
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">Cody Coderson</h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">&#60;Coder &#47;&#62;</h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 md:text-xl max-w-lg mx-auto">Code, Coffee, Cattlestar Calactica</p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <Link href="https://www.twitter.com" target={"_blank"}>
                <AiOutlineTwitter />
              </Link>
              <Link href="https://www.linkedin.com" target={"_blank"}>
                <AiFillLinkedin />
              </Link>
              <Link href="https://www.github.com" target={"_blank"}>
                <AiFillGithub />
              </Link>
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={deved} layout="fill" objectFit="cover" alt="picture of me" />
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white">Services I offer</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Apps and websites and <span className="text-teal-500">stuff</span>.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              What kind of stuff you ask? Ya know... dev type stuff. idk Just hit me up and let&apos;s chat.
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
              <Image src={design} width={100} height={100} alt="3d logo" />
              <h3 className="text-lg font-medium pt-8 pb-2">Pretty. Good. Designs.</h3>
              <p className="py-2">They are really nice ok. Seriously I mean look at that thing. Adding more text so this div is bigger.</p>
              <h4 className="py-4 text-teal-600">Design Tools I Use</h4>
              <p className="text-gray-800 py-1">Gimp</p>
              <p className="text-gray-800 py-1">MS Paint</p>
              <p className="text-gray-800 py-1">Paper and Pencil</p>
              <p className="text-gray-800 py-1">My imagination</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
              <Image src={code} width={100} height={100} alt="3d logo" />
              <h3 className="text-lg font-medium pt-8 pb-2">Pretty. Good. Code.</h3>
              <p className="py-2">I code some good code. The code I code is good. If you want good code, I&apos;m your guy.</p>
              <h4 className="py-4 text-teal-600">Code Tools I Use</h4>
              <p className="text-gray-800 py-1">Notepad</p>
              <p className="text-gray-800 py-1">A keyboard</p>
              <p className="text-gray-800 py-1">A computer</p>
              <p className="text-gray-800 py-1">My imagination</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
              <Image src={consulting} width={100} height={100} alt="3d logo" />
              <h3 className="text-lg font-medium pt-8 pb-2">Pretty. Good. Thoughts.</h3>
              <p className="py-2">I can consult you real good. Consult me for a consultation on my consulting.</p>
              <h4 className="py-4 text-teal-600">Consult Tools I Use</h4>
              <p className="text-gray-800 py-1">My brain</p>
              <p className="text-gray-800 py-1">My mouth</p>
              <p className="text-gray-800 py-1">My ears</p>
              <p className="text-gray-800 py-1">My imagination</p>
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white">Code things I code</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Apps and websites and <span className="text-teal-500">stuff</span>.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              What kind of stuff you ask? Ya know... dev type stuff. idk Just hit me up and let&apos;s chat. Did I already say that? ... ugh
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1">
              <Image src={web1} className="rounded-lg object-cover" width={"100%"} height={"100%"} layout="responsive" alt="screenshot of website" />
            </div>
            <div className="basis-1/3 flex-1">
              <Image src={web2} className="rounded-lg object-cover" width={"100%"} height={"100%"} layout="responsive" alt="screenshot of website" />
            </div>
            <div className="basis-1/3 flex-1">
              <Image src={web3} className="rounded-lg object-cover" width={"100%"} height={"100%"} layout="responsive" alt="screenshot of website" />
            </div>
            <div className="basis-1/3 flex-1">
              <Image src={web4} className="rounded-lg object-cover" width={"100%"} height={"100%"} layout="responsive" alt="screenshot of website" />
            </div>
            <div className="basis-1/3 flex-1">
              <Image src={web5} className="rounded-lg object-cover" width={"100%"} height={"100%"} layout="responsive" alt="screenshot of website" />
            </div>
            <div className="basis-1/3 flex-1">
              <Image src={web6} className="rounded-lg object-cover" width={"100%"} height={"100%"} layout="responsive" alt="screenshot of website" />
            </div>
          </div>
        </section>
      </main>
      <footer className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <p className="text-sm py-5 leading-8 text-gray-800 dark:text-gray-200 md:text-md text-center mx-auto">
          Over-engineered with Next.js and Tailwind ❤️
        </p>
      </footer>
    </div>
  );
}
