import Head from "next/head";
import Image from "next/legacy/image";
import deved from "../public/dev-ed-wave.png"
import { BsFillMoonStarsFill } from "react-icons/bs";
import { AiOutlineTwitter, AiFillLinkedin, AiFillGithub } from "react-icons/ai"

export default function Home() {
  return (
    <>
      <Head>
        <title>Cody Coderson</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10 ">
        <section className="min-h-screen">
          
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons">not sure what to put here</h1>
            <ul className="flex items-center">
              <li><BsFillMoonStarsFill className="cursor-pointer text-2xl"/></li>
              <li><a className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8" href="#">Resume</a></li>
            </ul>
          </nav>

          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium">Cody Coderson</h2>
            <h3 className="text-2xl py-2">&#60;Developer &#47;&#62;</h3>
            <p className="text-md py-5 leading-8 text-gray-800">
              Code, Coffee, Cattlestar Calactica
            </p>
          </div>

          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
            <AiOutlineTwitter />
            <AiFillLinkedin />
            <AiFillGithub />
          </div>

          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden">
            <Image src={deved} layout="fill" objectFit="cover" alt="picture of me" />
          </div>

        </section>
      </main>
    </>
  );
}
